package mysql

const (
	MYSQL_Int                = "int"
	MYSQL_Varchar            = "varchar"
	MYSQL_Text               = "text"
	MYSQL_Date               = "date"
	MYSQL_Datetime           = "datetime"
	MYSQL_Timestamp          = "timestamp"
	MYSQL_Time               = "time"
	MYSQL_Decimal            = "decimal"
	MYSQL_Float              = "float"
	MYSQL_Double             = "double"
	MYSQL_Bit                = "bit"
	MYSQL_Tinyint            = "tinyint"
	MYSQL_Smallint           = "smallint"
	MYSQL_Mediumint          = "mediumint"
	MYSQL_Bigint             = "bigint"
	MYSQL_Char               = "char"
	MYSQL_Tinytext           = "tinytext"
	MYSQL_Mediumtext         = "mediumtext"
	MYSQL_Longtext           = "longtext"
	MYSQL_Binary             = "binary"
	MYSQL_Varbinary          = "varbinary"
	MYSQL_Enum               = "enum"
	MYSQL_Set                = "set"
	MYSQL_Blob               = "blob"
	MYSQL_Tinyblob           = "tinyblob"
	MYSQL_Mediumblob         = "mediumblob"
	MYSQL_Longblob           = "longblob"
	MYSQL_Geometry           = "geometry"
	MYSQL_Point              = "point"
	MYSQL_Geometrycollection = "geometrycollection"
	MYSQL_Linestring         = "linestring"
	MYSQL_Polygon            = "polygon"
	MYSQL_Multipoint         = "multipoint"
	MYSQL_Multilinestring    = "multilinestring"
	MYSQL_Multipolygon       = "multipolygon"
	MYSQL_JSON               = "json"
	MYSQL_Year               = "year"
	MYSQL_DateTime           = "datetime"
	MYSQL_TimeStamp          = "timestamp"
)
